INSERT INTO staging.supermarket_sales_clean (
    invoice_id,
    branch,
    city,
    customer_type,
    gender,
    product_line,
    unit_price,
    quantity,
    tax_5_percent,
    total,
    sale_date,
    sale_time,
    payment,
    cogs,
    gross_margin_percentage,
    gross_income,
    rating
)
SELECT
    BTRIM(invoice_id),
    BTRIM(branch),
    BTRIM(city),
    BTRIM(customer_type),
    BTRIM(gender),
    BTRIM(product_line),
    unit_price::NUMERIC(10, 2),
    quantity::INTEGER,
    tax_5_percent::NUMERIC(12, 4),
    total::NUMERIC(12, 4),
    TO_DATE(sale_date, 'MM/DD/YYYY'),
    sale_time::TIME,
    BTRIM(payment),
    cogs::NUMERIC(12, 2),
    gross_margin_percentage::NUMERIC(12, 9),
    gross_income::NUMERIC(12, 4),
    rating::NUMERIC(3, 1)
FROM raw.supermarket_sales;